# Spring
server:
  port: 8080
  forward-headers-strategy: framework
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}           # Dirección del servidor RabbitMQ (o donde esté corriendo)
    port: ${RABBIT_PORT:5672}                # Puerto de RabbitMQ
    username: ${RABBIT_USERNAME:guest}           # Usuario de RabbitMQ
    password: ${RABBIT_PASSWORD:guest}           # Contraseña de RabbitMQ
    virtual-host: /           # Virtual host (normalmente "/" por defecto)
    exchange: ${RABBIT_EXCHANGE:requests-exchange}  # El exchange que usaremos
    queue: ${RABBIT_QUEUE:requests-queue}         # El nombre de la cola
    routing-key: ${RABBIT_ROUTING_KEY:requests-routing-key}  # La clave de enrutamiento para el binding
  main:
    banner-mode: console
    lazy-initialization: true

---
# ENVIRONMENT
environment:
  security-disable-ssl-cert-validation: ${DISABLE_SSL_CERT_VALIDATION:false}
  operator-id: ${OPERATOR_ID:66dfa51b4d8f56001517a04c}
  operator-name: ${OPERATOR_NAME:ArchivoFiel}
  domains:
    notifications-domain: ${NOTIFICATIONS_DOMAIN:http://notifications}
    centralizer-domain: ${CENTRALIZER_DOMAIN:https://govcarpeta-apis-83e1c996379d.herokuapp.com/apis}
    documents-domain: ${DOCUMENTS_DOMAIN:http://documents}
  service-retry:
    max-attempts: ${SERVICE_RETRY_MAX_ATTEMPTS:2}
  service-name: distribuidos/requests
  max-payload-size-in-mb: ${MAX_PAYLOAD_SIZE_IN_MB:10}
---
---
# Logging
logging:
  level:
    root: info
---
# Jwt
jwt:
  secret: ${JWT_SECRET:EPzuE1fY/zKURZ0eklR27ULNZTpAO51+dfDWt3iJRI7zyv+UdDjXaDlkV7X1I04r89mvdet5CAWSFkfrKv+fmg==}
  expiration: 3600000
